FROM {{ image }}
WORKDIR /app
RUN mkdir -p /opt/dpl
{% for layer in layers -%}
# Build Layer {{ loop.index }}
{% for file in layer.files -%}
{% if file == "*" %}
COPY app/ /app/
{% else %}
COPY app/{{ file }} /app/{{ file }}
{% endif %}
{% endfor -%}
{% if layer.script %}
{% for env_name in layer.env_names %}
ARG {{ env_name }}
{% endfor -%}
{% set heredoc = "DPL_BUILD_" ~ cuid() %}
RUN <<'{{ heredoc }}'
set -eu
{% for env_name in layer.env_names -%}
export {{ env_name }}
{% endfor -%}
{{ layer.script }}
{{ heredoc }}
{% endif %}
{% endfor -%}
{% if runtime %}
# Runtime
COPY artifacts/run.sh /opt/dpl/run.sh
{% if port is not none %}
EXPOSE {{ port }}
{% endif %}
CMD ["/bin/sh", "/opt/dpl/run.sh"]
{% endif %}
