FROM {{ image }}
WORKDIR /app
RUN mkdir -p /opt/dpl
{% for layer in layers -%}
# Build Layer {{ loop.index }}
{% for file in layer.files -%}
{% if file == "*" %}
COPY app/ /app/
{% else %}
COPY app/{{ file }} /app/{{ file }}
{% endif %}
{% endfor -%}
{% if layer.script %}
{% set name = "build-" ~ loop.index %}
{% set path = "/run/secrets/" ~ name %}
RUN --mount=type=secret,id={{ name }} /bin/sh {{ path }}
{% endif %}
{% endfor -%}
# Runtime
COPY run.sh /opt/dpl/run.sh
EXPOSE {{ port }}
CMD ["/bin/sh", "/opt/dpl/run.sh"]
