FROM {{.Image}}
WORKDIR /app
{{- range .Layers}}
{{- if .CopyArgs}}
COPY {{.CopyArgs}}
{{- end}}
RUN --mount=type=secret,id={{.SecretID}} /bin/sh /run/secrets/{{.SecretID}}
{{- end}}
COPY run.sh /opt/dpl/run.sh
CMD ["/bin/sh", "/opt/dpl/run.sh"]
